# Generated by Django 4.1.2 on 2022-10-09 14:34

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('upload', models.ImageField(upload_to='tests/static/uploads/')),
            ],
        ),
    ]
